dist: trusty
sudo: false
language: node_js
node_js:
  - "8"
env:
  global:
    - CC_TEST_REPORTER_ID=a67ba0670b4485538244f9d5bbddd978ab05bd87604c748a3229cd044fd30f78
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  directories:
     - ./node_modules
install:
  - npm install
before_script:
  - npm install -g codeclimate-test-reporter
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI --code-coverage
after_success:
  - codeclimate-test-reporter < coverage/lcov.info
